### ISSUE TITLE
Убрать зависимость от ReflectionClass

### ISSUE THREAD

**Issue by mlavrinenko** [maximaster/tools.events#2]
К обсуждению устранение зависимости от ReflectionClass.
Когда впервые делал подобную систему обошёлся get_class_methods

**Comment by mmjurov** [comment]
Есть одна проблемка. По задумке у нас есть некий "Базовый класс", который дает нам функциональность управления порядком вызова обработчиков, а также возможность обмена данными. В будущем, возможно, он будет дополнен и другим функционалом (что увеличит количество методов). Вопрос в том, как с помощью get_class_methods отделить методы класса с обработчикам от родительского "базового". 
Как еще один вариант - один класс с обработчиками может наследоваться от другого класса с обработчиками (или вообще от любого класса, хз зачем). Хотелось бы избежать навешивания событий на те методы, события на которые уже навешаны (избежать двойного обращения к тому же самому обработчику)

В случае с рефлексией это решается одной проверкой (хотя тут есть, что оптимизировать, конечно)

``` php
if ($method->class == $class->getName()) {

}
```

Мы точно знаем, что не навесим во второй раз обработчик из унаследованного класса. Тут можно еще добавить исключение для BaseEvent, но я пока не уверен, что там не будет каких-то встроенных обработчиков (хотя вряд ли).

**Comment by mlavrinenko** [comment]
Полагаю решение будет примерно [таким](http://ideone.com/J7tkpw): 

``` php
<?php

class Foo { function a() {}}
class Bar extends Foo { function b() {}}
class Baz extends Bar{ function c() {}}

$baz = new Baz;
$methods = get_class_methods($obj = $baz);
while($obj = get_parent_class($obj))
    $methods = array_diff($methods, get_class_methods($obj));

print_r($methods); // Array ([0] => c)
```

**Comment by mmjurov** [comment]
Проверил на живом проекте. Предлагаемый тобой вариант быстрее на 1-3% (тестил на проекте с одним набором обработчиков, потом с x10 набором обработчиков, результат тот же). Мне кажется это пока сомнительным выигрышем в ущерб читабельности. 
Еще мне не нравится тот факт, что нужно создавать экземпляр класса, ведь он по сути должен быть целиком статичен. А вдруг там будет случайный конструктор, который даст состояние классу обработчика, которое совсем не ожидается? С другой стороны, это может быть и плюсом. 
Я думаю, что лучше подумать в сторону оптимизации варианта с рефлексией, ничего особо страшного в ней нет

**Comment by mlavrinenko** [comment]
Объект создавать не обязательно, это я что-то по привычке написал. Если в том коде написать $baz = 'Baz'; - будет тоже самое.

Про скорость работы ты меня удивил) Честно говоря я об этом вообще не думал, главный посыл был убрать зависимость. Даже если бы без рефлексии код был чуть медленнее, я бы все равно предпочёл такой вариант

**Comment by mmjurov** [comment]
А чем рефлексия не угодила, если не секрет? Ведь это часть ядра 5й версии

> Если в том коде написать $baz = 'Baz'; - будет тоже самое.

угу.. что-то не обратил внимания, что get_parent_class() еще и с именами классов работает, а не только с инстансами.

**Comment by mlavrinenko** [comment]
> А чем рефлексия не угодила, если не секрет? Ведь это часть ядра 5й версии

Почему-то был уверен что для этого надо отдельное расширение php подключать О_о
Ну раз в коробке, то ОК. На замене не настаиваю :-)

**Comment by mmjurov** [comment]
Попробую на досуге без создания инстанса, потестирую. Если будет раза в 2 быстрее, то заменю конечно.

**Comment by mlavrinenko** [comment]
> С другой стороны, это может быть и плюсом

К слову для Невставая я все таки заморочился и написал для композера хук после генерации автолодера который подменяет его на наш класс (наследует от стандартного) и уже в нём для всех подцепляемых классов делается попытка сделать __staticConstruct
Так что там этот плюс можно будет использовать и без объекта

В планах когда-нибудь запулреквестить нормальную правку в сам композер, авось да примут

**Comment by mmjurov** [comment]
В связи с #4 нет никакой необходимости отказываться от ReflectionClass, т.к. для использования комментов потребуется использовать ReflectionClass :) Закрываю
