### ISSUE TITLE
Один обработчик на несколько событий

### ISSUE THREAD

**Issue by mlavrinenko** [maximaster/tools.events#4]
Нередка ситуация когда пишется одна функция на Update и Add события, т.к. код будет практически идентичен. Если постараться и особых ограничений не будет - точно идентичен.

В таком случае приходится в одном из классов добавлять метод который внутри вызовет другую реализацию. Но зачем он вообще нужен?

Предлагаю добавить что-то типа ярлыков на другие методы, например в классе пишем

``` php
static $linked = [
   'OnAfterIBlockPropertyUpdate' => [
      'UpdateFilter',
   ],
];
```

Т.е. из соседнего класса OnAfterIBlockPropertyUpdate прицепится метод UpdateFilter
Вообще для удобства думаю стоит предусмотреть несколько вариантов записи, в том числе и такую:

``` php
static $linked = [
   'OnAfterIBlockPropertyUpdate::UpdateFilter',
];
```

Само собой если вызываемый класс вне того же пространства имён, придётся указывать полный путь.

Плюс не забыть учёт $sort

**Comment by mmjurov** [comment]
я вот подумываю и тут с помощью рефлексии решить. Сейчас общепринятой практикой является конфигурирование в комментах (Symfony, Doctrine так делают). прям в phpdoc

С помощью ReflectionFunctionAbstract::getDocComment можно получить коммент и считать оттуда конфиг.

**Comment by mlavrinenko** [comment]
Тогда уж и сортировку там удобнее писать будет :)

**Comment by mmjurov** [comment]
> Тогда уж и сортировку там удобнее писать будет :)

Сделал сортировку в #5

**Comment by mmjurov** [comment]
Начал было делать, потом понял, что я не совсем правильно понял )

Нужно раздавать линки не на методы, а на события. Мы пишем одну единственную реализацию обработчика Add и Update, кладем ее по адресу \Event\Add и нужно заставить это же обработчик отработать по событию Update. 
Значит нужно делать линк не на какой-то другой метод, а на какое-то другое событие, заставляя этот метод сработать при другом событии, отличном от того, которое определилось по неймспейсу.

В качестве примера. Мы пишем метод Main\OnAfterIblockElementAdd и хотим указать, что этот метод нужно вызывать также при Update. Тогда с использованием phpDoc нужно будет определить следующий блок:

``` php
/**
 * @eventLink OnAfterIblockElementUpdate
 */
public static function OnAfterIblockElementAdd($arFields)
{

}
```

Я все правильно понял?

Обычно эти события находятся в одном модуле, поэтому пока не буду следить за модулем. Если же понадобится следить за модулем (например Add элемента инфоблока и Add товара каталога в одном методе), то нужно продумать какой-то синтаксис, который будет красиво управлять модулем (видимо не через пробелы, надо подумать и посмотреть у других). А когда такой синтаксис придумается и устоится, тогда можно и сортировку туда пропихнуть. Сейчас же сортировка и модуль будет забираться из вызываемого метода.

**Comment by mlavrinenko** [comment]
Согласен, eventLink будет опрятнее
Менять пространство имён думаю пока не нужно будет, когда нужно будет - тогда и подумаем. Пока таких ситуаций вроде как нет

**Comment by mmjurov** [comment]
Реализовано в ветке v1.x
Как только будет готов функционал из #1, сделаю релиз в master
