### ISSUE TITLE
Ошибка формирования обработчика события на видне

### ISSUE THREAD

**Issue by dermanov-ru** [maximaster/tools.events#9]
Проблема из-за разделителя дирректорий. На видне он отличается. 
Решение уже предусмотрено в классе, но есть ошибка.

`$relativeClass` получается из имени файла, которые обходит сейчас итератор. Поэтому там все пути становятся тоже виндовыми.
А потом этот путь разбивается по линуксовому разделителю.

Нужно исправить 
`$nestedClass = explode('/', $relativeClass);`
на
`$nestedClass = explode(DIRECTORY_SEPARATOR, $relativeClass);`

**Comment by mmjurov** [comment]
Залил в master. Не могли бы проверить работоспособность на винде? У меня пока нет возможности ..

**Comment by dvcarrot** [comment]
возможно связанная проблема: https://github.com/maximaster/tools.events/issues/10
